### ISSUE TITLE
Shared Hosting Ability!

### ISSUE THREAD

**Issue by DDynamic** [TechnicPack/TechnicSolder#186]
Hello,
How would I got about installing Technic Solder on a cPanel hosting account with no SSH?

**Comment by FlareHAX0R** [comment]
Uhh... #221 might conflict with shared hosting. It might have something to do with x10hosting.

**Comment by mcmielleman** [comment]
Also the update checker, i cant just copy the files to the server anymore, need to find a solution.

**Comment by Spartan-K97** [comment]
TechnicSolder already works on shared hosting, I know because I have been using it on shared hosting (openshift) for quite a while, best part is that it only needs a small gear which is 100% free without even having to put in credit details so cost certainly isnt an issue for this.
It is a pain to set up in some respects such as having to copy the public folder since shared hosting will generally have chosen the "public" folder for you and you cannot change but to get around this you just create TechnicSolder as normal and then copy the public folder to that of what the hosting uses ("repo" in the case of openshift).
As for doing this without SSH, if this were an easy thing to set up such as pressing a button to install then everyone would do it and you wouldn't be able to find out whether modpack creators actually know what the're doing.

**Comment by Dylan3304** [comment]
@Spartan-K97 That is why I just bought an OVH vps! :)

**Comment by sct** [comment]
Shared hosting is just a mess when it comes to running things like Solder. If you aren't paying for it I guess that's one thing, but if you are you can get a VM that can run Solder from DigitalOcean for $5/month that would happily and easily run Solder.

**Comment by Spartan-K97** [comment]
it runs happily and easily on shared hosting, the only problem was figuring out to copy the public folder, other than that it was the same as using it anywhere else.

**Comment by TheDoctorsLife** [comment]
If your paying more than $5 to shared host solder, it would be more worth your time to get an VPS. besides, $5 really isn't that much.

**Comment by Spartan-K97** [comment]
yeah, but fwee...

**Comment by TheDoctorsLife** [comment]
for anything less than $5 I can see the appeal, but lot of the hosts I saw, have some sort of policy about hosting files, (Looking at u hosting24) also, it's up to the hoster to secure your files and the mysql server, and when thier offering the service for free, security might not be their biggest concern. Also with a VPS at least you have full control of the server, even though it's virtual.

**Comment by Spartan-K97** [comment]
I am comparing mostly to redhat openshift because that is what I use so there is not a lot that I can say about other hosts and yes, I agree that not having full control of the server can get annoying at times but for the purposes of TechnicSolder it is more than sufficient.
As for the security, it is hosted on the same machines as fully paid services so I am sure that they will be thinking about security.
In general I agree that VPS is a better choice but for the purposes of TechnicSolder I think that a small shared host is sufficient unless you are expecting your modpack to be in the top rankings where it needs greater speeds to keep up with all of the downloads.

**Comment by spannerman79** [comment]
Usually if you are running a solder install more then likely you are running some sort of forum system.  So a low tier share hosting provider won't suit you anyway for your forum/website.

But yes, a shared hosting ability (for hosts that provide the needed resources for solder eg ram & cpu) would be handy.  I've got a business shared hosting plan (now) and they provide ssh but not git access - so when the next update from `0.7.2.2` comes I'll have to figure something out

**Comment by p0kefreak** [comment]
hey there. i know this is an old post but if your still wanting a solder host i currently am renting a solder server and can create you a user account so you can host your modpack easily. i charge $8 per month per modpack. pm me if your interested

**Comment by Jerlag01** [comment]
$8 per month per modpack, expensive if you ask me, you can just get a free subdomain on noip.com link it to your home and set an old pc as linux server with solder installed. Serious man, i've got 6 modpacks if i would go to you then that costs me $48

**Comment by skwerlman** [comment]
@p0kefreak @Jerlag01 This is an issue tracker for solder, not a forum. Please take off-topic conversations (and especially advertisements) elsewhere.
