### ISSUE TITLE
A git style of modpack distribution

### ISSUE THREAD

**Issue by scj643** [TechnicPack/TechnicSolder#203]
Ok this might not belong her but people might see it.

New idea for a minecraft modpack delivery. A git style system that would use git as it's core.

**Comment by FrancisSayer** [comment]
As someone who uses git for handling the modpacks that run on our servers, I would love something like this, even if it was a completely different platform..
We used to have a python script that copied the mods from the git repo on Master to the mods folder in Solder. But considering it still requires a degree of manual input, it kinda annoys me since I'm an all-or-nothing kind of guy

**Comment by GenPage** [comment]
git is a version control system, not a binary file manager. A new distribution method is not something we are looking towards because it would require a re-work of our entire launcher-solder combo.
