### ISSUE TITLE
Attempted to extract file modpack-slug-1.0.zip, but it did not exist

### ISSUE THREAD

**Issue by FlareHAX0R** [TechnicPack/TechnicSolder#240]
I'm not sure if this is a Technic Launcher problem or a setup problem, but I get this error with my solder modpack:
Error unzipping a file for the following pack: mxSurvival Reloaded 2
Attempting to extract file mxsurvival-reloaded-2-1.0.zip, but it did not exist
Please consult the modpack author.

Please help me with this.
Modpack: http://www.technicpack.net/modpack/mxsurvival-reloaded-2.563515

**Comment by TheDoctorsLife** [comment]
http://mxsurvival.x10host.com/index.php/api gives me a 404, make sure your solder is setup correctly

**Comment by FlareHAX0R** [comment]
@TheDoctorsLife http://mxsurvival.x10host.com/public/index.php/api
Thats what the platform API link is set to.

**Comment by GenPage** [comment]
"Attempting to extract file mxsurvival-reloaded-2-1.0.zip"

This is an indication that the launcher doesn't think the pack is a solder pack and is instead try to download the pack zip from where its location is stated on the Platform.

The problem is your api returns a 404 with a **trailing slash** as indicated here:

Works: http://mxsurvival.x10host.com/public/index.php/api
Doesn't work: http://mxsurvival.x10host.com/public/index.php/api/

This is most likely a web server issue.

**Comment by FlareHAX0R** [comment]
Going to hostinger then...

**Comment by TheDoctorsLife** [comment]
You want to make sure that no one can access your solder files like /app

**Comment by FlareHAX0R** [comment]
How?

**Comment by Tsukiumy** [comment]
http://mxsurvival.x10host.com/
if i'm not wrong, your repo is out of the public folder.

**Comment by TheDoctorsLife** [comment]
using an .htaccess or setting the file permissions so public can't read them.
