### ISSUE TITLE
Minimal ports problem

### ISSUE THREAD

**Issue by TheGeekdu74** [TechnicPack/TechnicSolder#287]
Hello... again and again... I have just a question, this adress : http://odysse.myftp.org:46000/TechnicSolder/public/index.php doesn't works because the port 46000 is not listen on my Debian, but how to change that ? How to change the listening port of the TechnicSolder ?? (PS : I'm french so I have bad english sorry) I think the Solder needs to open a port to works, so what can I change this port ?

Help me please ;(

**Comment by TheDoctorsLife** [comment]
If you use something like http://translate.google.com It'd be eaiser, since you type in french, and we see (somewhat) accurate english, or just put plain french on here, and We'll do the translate part. This way your problem can get fixed faster.

Si vous utilisez quelque chose comme http://translate.google.com Ce serait eaiser, puisque vous tapez en français, et nous voir (un peu) précise anglais, ou tout simplement mettre brut français ici, et nous ferons le traduire partie. De cette façon, votre problème peut se fixe rapidement.

**Comment by TheGeekdu74** [comment]
Okay, but Google trasnlate is pissashit, so I don't use it, I translate by myself. Whatever, I found the issue, I think, I set the wrong port on apache2, because the port of apache2 is linked to /var/www/ but I don't know that before.
