### ISSUE TITLE
TechnicSolder Modpack showing as offline

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TechnicPack/TechnicSolder#338]
im get the error where the Modpack is shown offline, and it shows 
![yqx6abz](https://cloud.githubusercontent.com/assets/4357903/6545800/653bdbc2-c556-11e4-9295-e296a797d7eb.jpg)

and also the API Link shows 401 error http://api.technicpack.net/modpack/wg-atlas

**Comment by GibbsFrance** [comment]
Hi,

What is the link of your Solder ? My modpack is in my Solder and TechnicPack return the same result,  so it's not probably a bug of TechnicPack API.

**Comment by xH3LLRAIZ3Rx** [comment]
heres my Solder API link http://solder.windmillgaming.net/api

**Comment by GibbsFrance** [comment]
Have you at least one public build ? If you go to
http://solder.windmillgaming.net/api/modpack/wg-atlas you can see
recommended and latest build but empty list of builds. Try to set one build
to public and published.

**Comment by xH3LLRAIZ3Rx** [comment]
its all public and published, even on the TechnicSolder it shows no builds 
![njxpmc2](https://cloud.githubusercontent.com/assets/4357903/6548465/d77e3d50-c5b6-11e4-8c6b-e484f09ac333.jpg)

**Comment by xH3LLRAIZ3Rx** [comment]
oh lol, didnt know you have to click Publish, it now shows, let me test :D

**Comment by xH3LLRAIZ3Rx** [comment]
ok its Fixed :D

**Comment by Pyroglyph** [comment]
@xH3LLRAIZ3Rx Which page is the 'Publish' button on? I have this problem.

**Comment by EntranceJew** [comment]
@Pyroglyph 
You have to navigate to the modpack page, usually this is /modpack/view/MODPACKNUMBERHERE
![the publish button](http://i.imgur.com/lktV10U.png)

You have to individually publish each build.

**Comment by Pyroglyph** [comment]
I have published both builds (1.1 and 1 are identical, 1.1 was just to see if creating a new build would help. It didn't.) and it still shows as offline.
![image](https://cloud.githubusercontent.com/assets/9498104/9824491/1623a990-58c5-11e5-9988-38001c257ebd.png)

**Comment by EntranceJew** [comment]
@xH3LLRAIZ3Rx  It seems like your launcher isn't able to reach your modpack api correctly. Is your API returning a response similar to what was mentioned earlier in the conversation chain?

**Comment by Pyroglyph** [comment]
My /api/modpack/modpackname is in the exact same format as the one on the previously mentioned WindmillGaming api thing as it is right now (http://solder.windmillgaming.net/api/modpack/wg-atlas) <-- that one isn't mine because my server is bugging out right now but it was working fine 5 mins ago when I was testing it.

**Comment by Pyroglyph** [comment]
@EntranceJew Well it seems my modpack works now. Time heals all I suppose. However, it struggles to download one mod which I'm really confused about (I can download it fine from the direct link it supplies me in the error message so I don't see what the problem is). I've removed it from the pack so now I have to wait another half an hour or something so for Technic to update it's packs.

**Comment by EntranceJew** [comment]
If I had to guess, either the mod was packed incorrectly or the file is too big to download before timing out through the technic client. I'd take it up with the peeps in the technic irc. I'm glad things are working out! :+1:

**Comment by Pyroglyph** [comment]
@EntranceJew Oh, and it was going so well. I removed the mod from the pack and it manages to finish downloading the rest of the mods. Installing takes unusually long but when it reaches 100% the Play button does not appear. It is still the Install button. Clicking it just downloads and installs the mods again. Could it be that Forge might not be installed? I don't ever remeber configuring a Forge version.

**Comment by Pyroglyph** [comment]
@EntranceJew Out of pure luck I think I found the problem. I went to .techinc/modpacks/solar-survival and what do I find? Every single mod extracted into .technic/modpacks/solar-survival assets, classes and all. I fail to see how this is even useful and why Technic made Solder this way. I'm going to re-read some docs and hopefully try and fix this mess.

**Comment by EntranceJew** [comment]
Well, the mods are supposed to be extracted there, from the zips [in a way that matches how you would install them on a client](http://docs.solder.io/docs/zip-file-structure) -- pay careful attention to the part that says the forge universal launcher must be installed as a mod in the modpack under a special directory otherwise you won't actually be able to launch the game.

**Comment by Pyroglyph** [comment]
@EntranceJew I'm trying to write a batch script to convert all my incorrect mods to the solder format (foreach zip, rename it to jar, make a mods folder for it and put it inside, then make a zip with its name and put the mods folder in that zip, then delete the original mods folder with the jar to save space) but it's really difficult.

**Comment by Razorskills** [comment]
if you want, there is an auto zipper bat file that works with 7 zip that might help you out if you want it: https://gist.github.com/Drethic/5ac899e7c45545067832

**Comment by Pyroglyph** [comment]
You may be a little too late because I wrote my own batch script to do it for me XD
