### ISSUE TITLE
Mysql solder error

### ISSUE THREAD

**Issue by fuwwy** [TechnicPack/TechnicSolder#379]
On add a mod. I have the  option  (donator url) Im not use this because is only to technic official.
But on add my modpack I receive one mysql error "not found donatelink...."
And on add a modpack as the same error with other tables (background_url, logo_url, icon_url)
Im create the tables and works but this error should be fixed

**Comment by spannerman79** [comment]
This is related to #378
You cannot use shared webhosting

**Comment by Rhodizzle** [comment]
FWIW, I'm using solder on GoDaddy and it's working flawlessly, including the composer/artisan bits required to setup/upgrade. I recently migrated from the default sqlite3 database to mysql and then did an upgrade 0.7.2.2, all without issues.

**Comment by spannerman79** [comment]
@Rhodizzle you are extremely lucky then.
The majority of shared webhosting cannot be used.
I must point out that officially solder does not support shared webhosting due to several security options being forced by wehbhosts which interferes with how solder operates.

If you have managed hosting - such as DreamHosts [VPS Hosting](https://www.dreamhost.com/hosting/vps/) you can use solder as you can configure the VPS to how you see fit.  Only reason why I suggest it is because of cost, and its very simple and easy to setup a `.phprc` file to outline your needs.

**Comment by spannerman79** [comment]
@GenPage please close due to inactivity
