### ISSUE TITLE
What the heck is this?

### ISSUE THREAD

**Issue by DahDude** [TechnicPack/TechnicSolder#380]
I don't understand this at all. First of all, I see 20 files that do who the heck knows what!! Maybe an installer might help. If you guys have time to make the Technic launcher and this I hope you can find the time to make an installer. Seconds, how you can not support Windows, its like one of the 2 most commonly used systems. I'm not gonna buy a Mac just to run Solder Io on it, 1 - That's a waste of money. 2 - It just purely doesn't make sense that you would leave out support for one of the most commonly used systems that exist. Even worse, Windows computers usually contain Ubuntu and setting up this on their requires buying a Digital Ocean Droplet. Part of me feels this is just setup partnership with Digital Ocean to make money off of people using Windows and Ubuntu. So until this thing has a FREE installer. Its not happening.

**Comment by Razorskills** [comment]
Installing Linux on a pc is free. (although i think there is a few you can purchase) But debian is free, linux Mint.. etc. This is software made for experienced users, almost everyone that uses it, uses linux. Some people have been able to figure out how to set it up for window, it is possible I think. But nobody will help you set it up for windows since it has been developed on linux. It is supposed to be set up on a dedicated server computer, most people use a vps, sometimes they can be as cheap as 2 bucks a month. Or if you have an extra machine lying around and don't have shitty upload speeds. you could use that. Nobody is going to hold your hand. If you can't figure out how to set solder up, just use the easy modpack zip system that can be set up on their site.

**Comment by spannerman79** [comment]
@DahDude where do you get the idea that there is a partnership with Digital Ocean?
There are MANY other locations where you can get a VPS.  Use google to find one. If you cannot use a search engine then I suggest that you follow what @Razorskills suggested in using the easy modpack zip system

**Comment by TheDoctorsLife** [comment]
@DahDude The main reason for not support Windows is to keep inexperienced users away from it and making the Technic platform no good. While it is possible to install on windows (I helped a guy do that) It's just easier by far to use Linux, aka the reason why it's suggested. The reason why digital ocean is suggested because of how cheap it is compared to most shared hosts.

**Comment by NitroxydeX** [comment]
Let me think about it... who the heck uses windows for a webhosting-solution?!
Solder is for experienced users and this is what linux is for. Easy Going.

**Comment by TheDoctorsLife** [comment]
Even so, I only got good at linux cause of solder (Now I run my own 24/7/365 VPS)
