### ISSUE TITLE
Can not update or change anything.  Readonly database? wtf.

### ISSUE THREAD

**Issue by MasterWofleh** [TechnicPack/TechnicSolder#395]
SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (SQL: update "user_permissions" set "solder_full" = 1, "solder_users" = 0, "mods_create" = 0, "mods_manage" = 0, "mods_delete" = 0, "updated_at" = 2015-05-22 00:01:01, "solder_keys" = 0, "solder_clients" = 0, "modpacks_create" = 0, "modpacks_manage" = 0, "modpacks_delete" = 0 where "id" = 1)

I was talking to @GenPage on irc, but it must have been late for him as he was come and go.  Need to figure out this issue.  

Using sqlite.  Been all day installing this, to not be able to use it.

**Comment by disconsented** [comment]
http://stackoverflow.com/questions/3319112/sqlite-read-only-database

**Comment by MasterWofleh** [comment]
Okay, so what do I need to do to set the perms?  That link doesnt help.

**Comment by MetalBreaker** [comment]
@MasterWolfeh, you have to chmod production.sqlite (the SQLite database). Sorry if this is old and my answer won't get noticed, but here's the solution anyway.
1. Navigate to your Solder Installation
2. While located in your Solder Installation path, go to the app folder
3. Go to the database folder
4. Run the command "chmod 600 production.sqlite" (enter it without the quotes).
5. Fixed!

**Comment by MasterWofleh** [comment]
@MetalBreaker Wrong, Not fixed.

**Comment by TheDoctorsLife** [comment]
Try chown -R youruser:www-data SolderInstallFolder/ & chmod -R 776 SolderInstallFolder/. Let me know if this helps/doesn't work.

**Comment by MetalBreaker** [comment]
@MasterWofleh, sorry if I was being rude and like "HERE'S MY SOLUTION! IT'S BETTER THAN ANYONE ELSE'S!!! IT WORKS 100%". Really sorry for that. Hmmm... I could set it up for you, since I already set up 3 Solder installations for my friends. I can do that on a free host, and I'll do that for you for free. If you want to discuss about it, add me on steam, MetalBreaker, the TF2 spy picture.
@TheDoctorsLife, hmmm... Interesting solution. Could you explain what the chown command does? I'll explain the chmod one: 
Chmod is a terminal command used by Linux and Mac (by Unix systems). It sets the permissions of files. Possible permissions are: Read, Write, Execute, and possible user groups are: Owner, Group and Others. The -R command TheDoctorsLife posted means recursive (meaning that it will chmod the directory, along with the files in the directory, subdirectories, subdirectories of subdirectories, files of subdirectories, files of subdirectories of subdirectories etc...). I also use chmod frequently. :)

**Comment by TheDoctorsLife** [comment]
chown changes the owner, so change owner or chown, -R means it'll be recursive

**Comment by MetalBreaker** [comment]
@TheDoctorsLife, thanks for the explanation! I don't think people like executing commands that they don't know what they do :D  :+1:

**Comment by TheDoctorsLife** [comment]
/me looks at his perfectly running VPS & home pc, where he has run many, many untested commands.
I do make plenty of backups though, so I can afford it.

**Comment by MasterWofleh** [comment]
@MetalBreaker Will be sending you a friend request shortly. I have my own VPS so, that's where it will be installed.

@TheDoctorsLife I am going to attempt this method first to see if that cures the issue.

**Comment by MasterWofleh** [comment]
Fixed by @GenPage
