### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by Krahazik** [TechnicPack/TechnicSolder#431]
Opening the TechnicSolder web control panel, the panel is missing images.
Ubuntu Linux 15 running Apache2 and PHP5 with MySQL database

![150811-missing-images](https://cloud.githubusercontent.com/assets/7703706/9206824/ebe61fb4-401e-11e5-99d4-8ecaaeb08f41.jpg)

**Comment by Tomson124** [comment]
There are no images on solder as far as I know (except the background)
I think there is a problem with your css files for Sodler, they should do the whole designing thing for Solder but at your instance they are not loaded or not even there. You could check if the browser found them if you "right click" some where in your browser and choose "examine element" (or something like it) and then look under "console" if there are any errors... maybe you could post them here.

Excuse me english, I'm a German student ;)

**Comment by Krahazik** [comment]
I foun d the problem, I was loading __"TechnicSolder/server.php"__
When I load __"TechnicSolder/public/index.php"__ everything looks proper.

**Comment by Tomson124** [comment]
oh okay good to know you got it fixed.
Maybe you close this issue then?

**Comment by skwerlman** [comment]
That URL means that your public root is in the wrong place. That's not a
good thing, since it means all your configuration data is publicly visible.
On Aug 12, 2015 4:55 PM, "Thomas Wolfgruber" <notifications@github.com>
wrote:

oh okay good to know you got it fixed.
Maybe you close this issue then?

—
Reply to this email directly or view it on GitHub
<https://github.com/TechnicPack/TechnicSolder/issues/431#issuecomment-130445090>
.
