### ISSUE TITLE
MD5 Problem

### ISSUE THREAD

**Issue by TheNoim** [TechnicPack/TechnicSolder#444]
Hello,
I have this MD5 Download Error:
http://www.bilder-upload.eu/show.php?file=cdd9f8-1440712287.png
But in the Solder is the MD5 right. I already Rehash:
http://www.bilder-upload.eu/show.php?file=43b84b-1440712311.png
Can somebody help me ?

Best Regards Nils

**Comment by Indemnity83** [comment]
I just downloaded the file and the checksum comes out e9cf2e... so it really doesn't match. 

It looks like you're using the development branch of TechnicSolder, not the master. When you hit the rehash button what message pops up at the top of the page? I would expect it to say "MD5 provided does not match file MD5". 

If this is the case, then there are two things you can do:

1. Clear the current hash from the input field and click rehash, it should update correctly (assuming the zip file isn't too large)
1. Put the correct hash (below) into the input field and click rehash, it *should* update and return a success message

     MD5: cf2e0e5d10e05252759aa61de974a9

I'm curious how you ended up with the wrong MD5 in there in the first place. My best guess is that you changed the file on the server after the first hash? If that's the case, this is expected behavior.

**Comment by TheNoim** [comment]
Thank you for this help :+1:
