### ISSUE TITLE
404 error on fresh Solder install?

### ISSUE THREAD

**Issue by Pyroglyph** [TechnicPack/TechnicSolder#447]
So I followed the instructions on http://docs.solder.io/ and I have my Solder installed to /usr/share/nginx/html. When I go to solder.app/public (which should take me to the dashboard), it directs me to solder.app/public/dashboard (as it should do) but throws a 404 error instead of actually displaying the dashboard. No idea where I've gone wrong and this is my third attempt at installing Solder so I'm getting pretty tired of this now. Any ideas?

**Comment by skwerlman** [comment]
your nginx logs should have more info, assuming you've enabled them

**Comment by DavidJudge** [comment]
I have this same issue;

I've successfully followed the guide found at http://docs.solder.io/, running on Ubuntu 14.04. I do have mcrypt enabled, and I'm using nginx and LEMP.

My problem is when I navigate to "http://serveraddress/TechnicSolder/public", I am getting redirected to "http://serveraddress/TechnicSolder/public/dashboard" and then a 404 error since that doesn't exist. I have enabled file permissions 755 for the whole html folder, and can run a directory listing on the TechnicSolder directory (which has the same permissions as the public directory). I don't know if there is a step in database configuration that I have missed, as I haven't touched the mysql database I have installed.

Any assistance with this would be appreciated; after 4 days I'm getting a bit frustrated,

**Comment by GenPage** [comment]
Hey @DavidJudge,

Please see the example web configuration files: http://docs.solder.io/docs/example-web-server-configs

* You do not have your application set to use the public folder as the root web folder.

* The 404 is most likely due to try_files redirecting to a 404 instead of the index.php file in the public folder, as shown in the example web configs.

Those two things should fix your issue :)

Cheers

**Comment by DavidJudge** [comment]
Wow I feel like such a tool for not checking the examples - I thought that since I'd followed the guide I'd be good! 

Thanks very much for the quick response GenPage, that's worked well so far. I can now get to the login page successfully. However, when I try to log in I'm getting "Error in exception handler." So I've obviously missed something else :(

Thank you very much for your assistance and patience with me!

**Comment by DavidJudge** [comment]
The fault was with my database permissions. These are now corrected - I gave the /app/database and /app/database-sample directories 777 permissions and they're working.

I presume I'd be able to get away with 766 permissions for the database director in my production environment?

**Comment by GenPage** [comment]
775 is the what you should be using. If that breaks it again, the owner/group is not set to the web server user (www-data, etc)

**Comment by DavidJudge** [comment]
Thanks very much GenPage :smile: Best support ever! :+1:

**Comment by GenPage** [comment]
You are very welcome! 😀
