### ISSUE TITLE
Missing Post Data when rehasing mod versions.

### ISSUE THREAD

**Issue by Misterio77** [TechnicPack/TechnicSolder#473]
Hey there,
I'm here to report a (quite annoying) bug i found after updating solder to the latest version:
As the title says, when rehashing any mod versions i get a red message that reads:
"Error: Missing Post Data".

Thanks,

**Comment by GenPage** [comment]
This is fixed in the dev branch. Issue usually tends to be a CloudFlare redirect.

**Comment by Misterio77** [comment]
Oh. I'll probably use the dev branch, then. Thanks a lot!

**Comment by Towsty** [comment]
Did you ever get this figured out?

**Comment by spannerman79** [comment]
> Did you ever get this figured out?

To point out the obvious - did you in fact read the previous comments?  Like for example @GenPage comment being and I quote;
>This is fixed in the dev branch. Issue usually tends to be a CloudFlare redirect.

**Comment by Towsty** [comment]
Yes I read the post. The question I have comes from the fact that using version 0.7.2.2 (the stable release) on the server that I actually host my modpack from works fine. I setup a test server for something else, setup solder with the same version and ran into this issue. I installed the dev-master branch to a clean instance to test and see if this was any different, it was not. Same issue arose. The reason I ask is that this issue was closed by mysterio in October, according to Git and packgist there have not been any changes to any branch since the beginning of September. 

So if this is fixed in a dev branch, is there a different way to get it than the way that is listed in the solder documentation? Or is there a different source somewhere? 

If there is no alternative repo anywhere, how did misterio get around this?
