### ISSUE TITLE
Error 500 when adding new modpack version

### ISSUE THREAD

**Issue by Tencao** [TechnicPack/TechnicSolder#491]
So everytime I try to make a new modpack build for my pack, it gives me the error 
"500 -  Invalid argument supplied for foreach() (View: E:\Websites\Solder\app\views\modpack\build\create.blade.php)"

This has been working fine for ages, but suddenly stopped working. Any clue why?

OS - Windows server 2012
Technic Solder version - 0.7.2.1

**Comment by spannerman79** [comment]
Logs? Solder version?

I will say though officially windows installs are not supported, as outlined in the solder docs

**Comment by Tencao** [comment]
I know windows installs are generally not supported, but since we've had solder working this long, I don't think this is a windows specific issue. And the solder version and error is in the first post. If it has any logs, just tell me where they should be and I'll grab them for you.

**Comment by spannerman79** [comment]
Typically the logs are under `./app/storage/logs`

And I have already stated - that is an old solder version, update to `v0.7.2.2` - the current non dev version.

**Comment by Tencao** [comment]
It's one minor version out of date, and I didn't see anything in the changelog that fixes this issue, so I don't think that would matter for this issue. 

http://pastebin.com/536R7Ax9

This is the full log for today

**Comment by abaw7** [comment]
Upon reading of the commits since his version of solder and the current. This issue has not already been fixed. If I'm wrong, feel free to correct me, however I don't believe that his version is the problem here.

For convience's sake, here's a list of the commits from the increment version v0.7.2.1 to v0.7.2.2:

https://github.com/TechnicPack/TechnicSolder/commit/537ba1afc6a4f25deb30bfa2ac637ddbdcd207f2
https://github.com/TechnicPack/TechnicSolder/commit/3d10429af6af097ac8999e113c7fbf9850b952e9
https://github.com/TechnicPack/TechnicSolder/commit/bcac5fbe04768df48fd4cff8dd8855090ace9229
https://github.com/TechnicPack/TechnicSolder/commit/8f4a521784a1c144dd7ca3539e17772d4f5b848d
https://github.com/TechnicPack/TechnicSolder/commit/63194ca8d63e74ab020fa5c7a9e85c7423ffd5fd
https://github.com/TechnicPack/TechnicSolder/commit/582a66c8a35a316f74d2b2e4fd0e8912a05095bf
https://github.com/TechnicPack/TechnicSolder/commit/3dd6721d2b307c8bbf20a45741fc815c8c383836
https://github.com/TechnicPack/TechnicSolder/commit/1410ed7556f03c2c96546457cf143e97ae31a6c5

**Comment by spannerman79** [comment]
The reason why (I assume) that @GenPage or any other of the contributors have not commented is because of the following;



> OS - Windows server 2012
> Technic Solder version - 0.7.2.1

Regardless of what supposed minor version you have an update is needed.

Secondly your OS - it states **clearly** on the solder docs that there will be no windows support given, and i will quote
>Windows installation is not supported (No help will be provided.)

More then likely it would be because of some Windows OS update or something else based on your OS that is the issue.  I have been running a solder setup now for nearly 6 months on CentOS non stop and not once have i had any issues .  Solder is pretty bulletproof and solid when run on the correct platform intended.

@GenPage I suggest this issue be closed based on incorrect deployment platform.

**Comment by Tencao** [comment]
Ok, first, please read my entire report, rather than one small detail and completely dismissing it based on that. We've had our solder install running for about a year now, and we've been on both linux and windows, and honestly, linux install of solder had more issues than our windows install, but thats a topic for another time. Also, I'm fully aware they dont support windows installation, but this is not about a windows installation, as we have a very well established install of it, with no help required. 

The main issue here, especially after what fixed it, seems to be a write error when it tried writing a new modpack version. Now, since they've made a ton of changes in regards to both memory requirement, and java requirement, there's a chance that solder miswrote one of these into the database, as upon manually adding a modpack version, it started to work again. Now, I want to clarify, this was NOT the first modpack version we tried adding, we have around 30+ modpack versions before this error even appeared, and has absolutely nothing to do with windows as a platform. This is a genuine bug with solder, and if I said the OS was linux, I can bet you wouldn't have even come here bashing on the issue simply because I mentioned windows. I don't appreciate you coming here with no intent on solving the problem, and instead trying to shoo me away simply because I reported an isuse I was experiencing, which last time I checked, the issues part of github is designed to report issues so devs can fix them, not ignore them, and this is a legit issue that could effect a number of users, not just me, and not just on windows. 

So @spannerman79 If you don't have anything constructive to add to this issue, then I ask that you don't keep replying here with the same mentality, and leave it to others, or even the devs to handle this issue, not you.

**Comment by Pyker** [comment]
Solder on Windows is officially unsupported, and this was a long time ago, so I'm closing this.
