### ISSUE TITLE
Error with Modpack Install

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TechnicPack/TechnicSolder#502]
I have Technic Solder on my Dedicated Server, when making a Modpack and trying to install it shows this: 
Error unzipping a file for the following pack: WG Uranium 
Attempting to extract file wg-uranium-1.0.zip, but it did not exist. 
Please consult the modpack author

What am I doing wrong here? could it be because of SSL?

Here's the apps/storage/logs: http://hastebin.com/revojoxewa.vbs
Here's the api link: https://solder.windmillgaming.net/api
Here's the api link for the modpack: https://solder.windmillgaming.net/api/modpack/wg-uranium

**Comment by spannerman79** [comment]
Possibly related to #498 if you are using a local repo

**Comment by xH3LLRAIZ3Rx** [comment]
ok, I see there is a Update so I will try and get back to you

**Comment by xH3LLRAIZ3Rx** [comment]
That sadly didn't fix the issue

**Comment by GenPage** [comment]
The Launcher does not detect your pack is a Solder pack yet. This could be due to caching issues in the API. It just needs time to expire. 

"Error unzipping a file for the following pack: WG Uranium 
Attempting to extract file wg-uranium-1.0.zip, but it did not exist. 
Please consult the modpack author"

As you can see the pack is still trying to download an entire zip as if it was not a solder pack

**Comment by xH3LLRAIZ3Rx** [comment]
How long will it take to expire?

**Comment by RubenRME** [comment]
> How long will it take to expire?
Do you have any information on this now @xH3LLRAIZ3Rx, want to know it myself as well

**Comment by GenPage** [comment]
Cache should be 1 hour maximum.

**Comment by masonato** [comment]
Every time a mod pack needs more than one gig of RAM it says I need the latest version of java which I already have.

**Comment by GenPage** [comment]
@masonato This is for Technic Solder, not for the Launcher. Please go to https://support.technicpack.net
