### ISSUE TITLE
Windows 10 Problem - I belive

### ISSUE THREAD

**Issue by sagarreddy2003** [TechnicPack/TechnicSolder#524]
When the launcher is opened, and after  I click play, it goes back to the launcher.

**Comment by RubenRME** [comment]
Way to vague and for someone to actually help you with your problem. You should explain your problem in detail.
Also, I'm using windows 10 as well, but I can't verify your problem because of the fact that, again, you've given no information.
Please go more in depth on this. E.g: what error message you get, what your steps are before this problem, launcher log, with what modpack this happens etc. That'll make the lifes of the actual developers a lot easier :)
I might be having the same problem as you by the way, but can't say.

**Comment by Razorskills** [comment]
This is also the Solder Repository and is not an issue tracker for the launcher.

http://www.technicpack.net/help

https://github.com/TechnicPack/TechnicLauncher
