### ISSUE TITLE
Technic Launcher not opening correct solder link

### ISSUE THREAD

**Issue by Pigatto17** [TechnicPack/TechnicSolder#642]
I have recently setup an instance of technic solder for a test mod pack and i'm getting a very strange issue. The launcher is trying 'http://tmm.flnet.org/TechnicSolder/public/api/modpack/' and getting nothing, but 'http://tmm.flnet.org/TechnicSolder/public/api/modpack' returns as normal. Any suggestions?

**Comment by nbartokos** [comment]
I had the same problem and it was really strange to fix it.. Unfortunately I can't remember, how I fixed this. I think i have reinstalled it and changed the apache server root directory to solder. So I have to call http://example.com/api/modpack instead of .../TechnicSolder/public/api/modpack and then It worked. But i think the problem is in the .htaccess file or laravel routes or a permission error. (try chmod -R 777 /var/www/html/TechnicSolder)

**Comment by spannerman79** [comment]
> try chmod -R 777 /var/www/html/TechnicSolder

**NEVER** give full recursive read/write/execute access to a base directory served by a web server daemon.

http://docs.solder.io/docs/getting-started#web-server-configuration

**Comment by Jerlag01** [comment]
indeed NEVER set the permissions recursively to 777. that will only cause more problems with security.
Try to change the user and group to www-data:www-data

`chown -R www-data:www-data /var/www/html/TechnicSolder`

If your webserver uses this user to execute itself then that should fix it.
