### ISSUE TITLE
Add ModVersion Error

### ISSUE THREAD

**Issue by teddy123434** [TechnicPack/TechnicSolder#652]
When I added the modversion to my Solder,then it jumped out a error!
How can i do for this?
![solder error](https://user-images.githubusercontent.com/20450622/35965309-79598d86-0cf5-11e8-8a98-5d3d77bce67d.png)

**Comment by Coding-Doctors** [comment]
@teddy123434 Perhaps you forgot to set a MD5?

**Comment by PPlayzMC02** [comment]
@Arzte I'm having the same issue. I've tried to generate an MD5, but it's not working.

**Comment by Indemnity83** [comment]
I can't download the file at the URL thats being generated, are you sure you have the file in the right place and are using the right version?

**Comment by Indemnity83** [comment]
Actually... I can't access your solder API at all

**Comment by PPlayzMC02** [comment]
@Indemnity83 Who are you talking to?

**Comment by Indemnity83** [comment]
Was speaking directly to the screen shot that @teddy123434 posted. 

@PPlayzMC02 is there any error that is generated when you try to submit the version that would be helpful to post here. I suspect that problem is that MD5 fails on the file, which could be caused by the file path being wrong, the file being inaccessible or the file being too large (memory overflow).

**Comment by PPlayzMC02** [comment]
@Indemnity83 Nope. It just says Error:. The file is less than 1 MB. The file path is correct, and it can be accessed.

**Comment by nbartokos** [comment]
Did you set the repo_location and mirror_link properly in the app/configs/solder.php file? If yes, please check your file permissions or set it with: chmod -R 777 /var/www/html/TechnicSolder (or your path)

**Comment by Pyker** [comment]
This should now either be fixed or give a much clearer error message.
