### ISSUE TITLE
Incompatible with subdirectories

### ISSUE THREAD

**Issue by forresthopkinsa** [TechnicPack/TechnicSolder#659]
Solder fails to run when not running as the web root.

Expected behavior is that it runs just fine in subdirectories.

The actual problem arises when trying to install the pack:

![image](https://user-images.githubusercontent.com/4433153/41305760-c73e98e0-6e28-11e8-9445-ebf8f0fd794e.png)

It responds with `Error unzipping a file for the following pack...`

**Comment by Indemnity83** [comment]
Installing TechnicSolder in a subdirectory is not a supported configuration; primarily because as you've pointed out it is not a supported configuration in Laravel 4.2 (the fix you've linked to is version 5.5) but also because it can significantly complicate troubleshooting.

Solder can easily be run under a subdomain, and is generally the recommended approach to be used.

**Comment by forresthopkinsa** [comment]
The only reason it fails is because of that `htaccess` file. Just because Laravel didn't used to provide support for non-default configurations doesn't mean it's a breaking change.

Subdomains are fine and dandy until you start running a slightly less simple setup, in which case it doesn't make sense to use subdomains over subdirectories.

**Comment by Jerlag01** [comment]
normal users follow the guide in the first place and don't screw around with "advanced" configurations.
Normal users also just install web applications to the right directory that is created by the webservice itself and not a seperate one that is somewhere located on the system

**Comment by forresthopkinsa** [comment]
@Jerlag01 You're right. This doesn't concern casual users who install Solder on Windows systems. This is for more heavy-duty use in dedicated headless systems.

Also -- I'm not sure what you mean by "the right directory that is created by the webservice itself and not a separate one". Can you elaborate on what you're trying to say with that? Are you suggesting that users should be placing the solder installation directly into an Apache-generated directory?

If so, I'm afraid that's not the case. Conventional wisdom suggests that with any kind of web installation, you should definitely be keeping the installation somewhere else on the system, and symlinking the necessary files to a virtual directory that Apache can access.

**Comment by Jerlag01** [comment]
i run solder also on a linux system, the windows part is just because i wondered if it would also work on there. but windows is out of the question here. 

"The right directory of the webservice": nginx has usr/share/nginx/html
apache has var/www/html
you told me that you made a symlink to the solder directory which means that you are not running solder in the default webservice directory. if you would then you wouldn't need to do that stuff like creating a symlink. 
Also you can keep different web appllcation from each other by just putting it a subdirectory in the default paths and configure your webserver correctly as it suggest in the guides.

**Comment by forresthopkinsa** [comment]
The configuration you're suggesting -- keeping all the files directly in the server installation -- is not correct. But that has nothing to do with this. None of this has to do with the issue above. If you want to argue about standard ways to run web servers, we can do it in Discord. I'm trying to submit a PR here, and all of this is just noise.

**Comment by Jerlag01** [comment]
well it's been denied as indemnity himself said:

nstalling TechnicSolder in a subdirectory is not a supported configuration; primarily because as you've pointed out it is not a supported configuration in Laravel 4.2 (the fix you've linked to is version 5.5) but also because it can significantly complicate troubleshooting.

Solder can easily be run under a subdomain, and is generally the recommended approach to be used.

just deal with it, it won't change

**Comment by forresthopkinsa** [comment]
@Jerlag01 Like I said, take the arguing somewhere else. A Github issue is no place for this. Leave it alone.

**Comment by forresthopkinsa** [comment]
Thanks @Pyker !
