### ISSUE TITLE
The requested URL /index.php/dashboard was not found on this server.

### ISSUE THREAD

**Issue by KR4NK3NSCHW3ST3R** [TechnicPack/TechnicSolder#93]
After upgrading to Apache 2.2.22 / PHP 5.4.4-14+deb7u7 i cant access the solder api any more. Error: The requested URL /index.php/dashboard was not found on this server.

Apache Error log (LogLevel debug):
[Sun Feb 09 20:55:39 2014] [error] [client XX.XX.XX.XX] File does not exist: /var/www/technicsolder/public/index.php/dashboard
[Sun Feb 09 20:55:39 2014] [debug] mod_deflate.c(615): [client XX.XX.XX.XX] Zlib: Compressed 305 to 232 : URL /index.php/dashboard

**Comment by Bysokar** [comment]
@everyone This is caused by "AllowOveride" in the Directory settings (default /etc/apache2/apache2.conf) not being set to something other than None (Default setting nowdays). I have set it to All because I cant seem to find a way to enable just rewrite.

@sct Maybe you can include this as a FYI in the solder install documentation?

**Comment by skwerlman** [comment]
@Bysokar @\everyone mentions the user everyone, not people in this thread.

**Comment by Bysokar** [comment]
That is absolutely ridiculous. Why would GitHub Allow that... or someone to even use the username! :( @skwerlman

**Comment by Bysokar** [comment]
Put in a Request to get that looked at by github.. Haha fingers crossed. It's stupid nor their business name so doubt they will be allowed to keep it.
@skwerlman
